### ISSUE TITLE
Download scripts incomplete?

### ISSUE THREAD

**Issue by meesfrensel** [marcpaga/nanopore_benchmark#6]
Hi Marc,

I want to reproduce the results from your paper. However, the download scripts seem incomplete. The download_verm.sh script creates fast5 and fastq directories, but doesn't move any files to them. What data did you use for training and for testing? And did you use the fast*_fail files as well as the fast*_pass files?

Large parts of the download_wick.sh script are commented out, is that intentional or should they be uncommented for downloading all data used for your evaluation?

Thanks in advance!

**Comment by marcpaga** [comment]
The verm (lambda phage) dataset was sequenced in house, that's why there weren't any download links. We uploaded the data to this repository: https://www.ncbi.nlm.nih.gov/sra/?term=PRJNA926802.

You can find which reads where used for training and testing here: https://github.com/marcpaga/nanopore_benchmark/tree/main/static/tasks

Sorry about the commented lines, I was doing some testing on some sections and accidentally committed that. You can uncomment those, or also keep most loops commented to download the data part by part.

**Comment by meesfrensel** [comment]
Thanks, that helps.

The verm dataset does include a download link, but I was confused by some of the contents. As far as I understand, the process is to convert the .fast5 files in the fast5_pass directory from multi-fast5 to single-fast5 files, resquiggle those, preprocess, etc., right? And I can discard the .fast5 files in the fast5_fail directory as well as all fastq files?

**Comment by marcpaga** [comment]
After you have resquiggled the data you can indeed discard the fastqs. Regarding discarding the fast5_fail, I think I did not use any of these but to be safe I would check if any of the reads in the fast5_fail match the read ids of the reads used in training/testing.

**Comment by meesfrensel** [comment]
I confirmed no failed reads are used:

```bash
cd data/verm/Lambda_phage/tmp/VER5940
grep fail sequencing_summary_AGD599_248f8352.txt | awk -F '\t' '{print $3}' | grep -f - ~/nanopore_benchmark/static/tasks/*
# no results
grep pass sequencing_summary_AGD599_248f8352.txt | awk -F '\t' '{print $3}' | grep -f - ~/nanopore_benchmark/static/tasks/*
# many results
```

Thanks for your assistance.
